<?php
//These are the application key and secret
//You can create an application, and then get this info, from https://dev.twitter.com/apps
//(They are under OAuth Settings, called "Consumer key" and "Consumer secret")
define('TWITTER_CONSUMER_KEY', $CONSUMER_KEY);
define('TWITTER_CONSUMER_SECRET', 'gYGIsdBhek4YUdd1KjKTaKBLfyd3Wn4XzglPKcGq1MUPk9MPp6');

//These are the user's token and secret
//You can get this from https://dev.twitter.com/apps, under the "Your access token"
//section for your app.
define('OAUTH_TOKEN', $OAUTH_ACCESS_TOKEN);
define('OAUTH_SECRET', $OAUTH_ACCESS_TOKEN_SECRET);


?>